config/routes.rb
AddressBook::Application.routes.draw do
 
  resources :entries 

  root :to => "entries#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
    belongs_to :entry
    belongs_to :address_type
    attr_accessible :address_type_id, :city, :state, :street, :zip, :entry_id

    validates :zip, :address_type_id, :state, :presence => true
    validates_length_of :zip, is:5
    validates_length_of :state, is:2
#    def state=(val)
#        write_attribute(:state, val.upcase)
#    end
#
#    def city=(val)
#        write_attribute(:city, val.titleize)
#    end
end

app/models/address_type.rb
class AddressType < ActiveRecord::Base   
    attr_accessible :name
end

    

app/models/avatar_uploader.rb
class AvatarUploader < CarrierWave::Uploader::Base
    include Cloudinary::CarrierWave
end

app/models/comment.rb
# class Comment < ActiveRecord::Base
#    belongs_to :entry
#
#    attr_accessible :content, :entry_id
#
#    def comment_time
#        return "Message left at #{Time.now}. " 
#    end
# end

app/models/email.rb
class Email < Url 
    validates :name, :email => true
    def self.prefix
       'mailto:'
    end

    def to_email
        return self.prefix + read_attribute(:name)
    end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :addresses,  :dependent => :destroy
  has_many :emails,     :dependent => :destroy
  has_many :webs,       :dependent => :destroy
  has_many :phones,     :dependent => :destroy
#  has_many :comments,   :dependent => :destroy

  accepts_nested_attributes_for :addresses,     :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :emails,        :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :webs,          :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :phones,        :allow_destroy => true, :reject_if => :all_blank
#  accepts_nested_attributes_for :comments,      :allow_destroy => true, :reject_if => :all_blank

  mount_uploader :avatar, AvatarUploader

  attr_accessible :first_name, :last_name, :title, :addresses_attributes, :emails_attributes, :webs_attributes, :phones_attributes, :avatar, :avatar_cache
  # attr_nested_attributes_for :addresses, allow_destroy:true, reject_if :all_black
  # validates_presence_of [:email, :first, :last_name]
  # validate_email_format_of :email  

  validates :first_name, :last_name, :presence => true

def first_name=(val)
   write_attribute(:first_name, val.titleize)
end

def last_name=(val)
    write_attribute(:last_name, val.titleize)
end

def full_name
    first_name + ' ' + last_name
end

end

app/models/phone.rb
class Phone < Url
#    validates_format_of :name, :with => /[0-9]{3}-[0-9]{3}-[0-9]{4}/
#    phony_normalize :name, :default_country_code => 'US'
#    validates :name, :phony_plausible => true
    def self.prefix
        'Tel: '
    end 

    def to_phone
       return self.prefix + read_attribute(:name)
    end
end

app/models/url.rb
class Url < ActiveRecord::Base
    belongs_to :entry
    belongs_to :address_type
    attr_accessible :name, :type, :address_type_id, :entry_id

    validates :name, :address_type_id, :presence => true
    def prefix
        self.class.prefix
    end

    def self.prefix
        # :nocov:
        raise "Virtual method 'prefix' called!"
        # :nocov:
    end
end

app/models/web.rb
class Web < Url
    validates :name, :url => true
    def self.prefix
       'http://'
    end

    def to_url
        return self.prefix + read_attribute(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  # GET /entries
  # GET /entries.json

  respond_to :html

  before_filter :get_entries
  before_filter :find_entry,     only: [:show, :edit, :update,:destroy]
  before_filter :build_children, only: [:new, :edit]
  
  def index
    respond_with(@entries)
  end

  def show
    respond_with(@entry)
  end

  def new
    respond_with(@entry)
  end

  def edit
    respond_with(@entry)
  end

  def create
    @entry = Entry.new(params[:entry])
    if(@entry.save)
        flash_notice('created')
    else
        # :nocov:
        build_children
        # :nocov:
    end
    respond_with(@entry)
  end

  def update
    flash_notice('updated') if @entry.update_attributes(params[:entry])
    respond_with(@entry)
  end
  
  def destroy
    @entry.destroy
    flash_notice('deleted')
    redirect_to entries_url
  end

  private
  # :nocov:
  def get_entries
      criteria = 
          if params[:search]
              param = "#{params[:search].downcase}%"
              ["lower(last_name) like? or lower(first_name) like ?", param, param]
          else
              ['substr(last_name,1,1) = ?', params[:initial]||'A']
          end
      @entries = Entry.where(criteria).order('last_name, first_name')
  end
  # :nocov:

  def find_entry
      @entry = Entry.find(params[:id])
      params[:initial] = @entry.last_name[0]
  end

  def flash_notice(msg)
      flash[:notice] = "#{@entry.full_name} #{msg}"
  end
  # :nocov:
  def build_children
      @entry ||= Entry.new
      @entry.class.reflect_on_all_associations.find_all do |a|
          a.collection?
      end.collect(&:name).each do |attr|
          @entry.send(attr).build
      end
  end
  # :nocov:
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
    # :nocov:
    def avatar(entry, width)
        if width > 100
            cl_image_tag(entry.avatar.blank? ? 'anonymous_tnjvj0.jpg' : entry.avatar,
                         width: width, crop: 'fill', radius: 20)
        else
            cl_image_tag(entry.avatar.blank? ? 'anonymous_tnjvj0.jpg' : entry.avatar,
                         width: width, crop: 'fill')
        end
    end
    # :nocov:
end

app/views/addresses/_delete.html.slim
unless f.object.new_record?
=f.input 'Delete', label_html: {class: 'inline'} do
  =f.check_box'_destroy'

app/views/addresses/_form.html.slim
.nested-fields
  fieldset
    legend Address
    
    = f.association :address_type, label:false
    = f.input :street, label:false, :placeholder=>'Street Address', :input_html=> {:style=> 'height: 50px'}
    = f.input :city, label:false, :placeholder=>'City', :input_html=>{:style=>'width: 8em'}
    = f.input :state, label:false, :placeholder=>'State', :input_html=>{:style=>'width: 5em'}
    = f.input :zip, label:false, :placeholder=>'Zip', :as => :string, :input_html=>{:style=>'width: 4em'}
    div class="checkbox"
      = f.check_box :_destroy
      = f.label :_destroy, "Remove"
     
    

app/views/addresses/edit.html.slim
h1 Editing address

== render 'form'

= link_to 'Show', [@entry, @address]
'|
= link_to 'Back', entry_addresses_path(@entry)

app/views/addresses/index.html.slim
h1 Listing addresses

table
  tr
    th AddressType
    th Street
    th City
    th State
    th Zip
  
    th
    th
    th

  - @addresses.each do |address|
    tr
      td = address.address_type.name
      td = address.street
      td = address.city
      td = address.state
      td = address.zip
    
      td = link_to 'Show', entry_address_path(@entry, address)  
      td = link_to 'Edit', edit_entry_address_path(@entry, address) 
      td = link_to 'Destroy', [@entry, address], :confirm => 'Are you sure?', :method => :delete

br

=
= link_to 'New Address', new_entry_address_path(@entry)
'|
= link_to 'Back to person', entry_path(@entry)

app/views/addresses/new.html.slim
h1 New address

== render 'form'

= link_to 'Back', entry_addresses_path(@entry) 
'| 
= link_to 'Test', new_entry_address_path(@entry)

app/views/addresses/show.html.slim
p#notice = notice

p
  strong AddressType:
  =@address.address_type.name

p
  strong Street:
  = @address.street
p
  strong City:
  = @address.city
p
  strong State:
  = @address.state
p
  strong Zip:
  = @address.zip




= link_to 'Edit', edit_entry_address_path(@entry, @address)
'|
= link_to 'Back', entry_addresses_url(@entry)

app/views/comments/_form.html.slim
= simple_form_for(@entry) do |f|
  - @entry.comments.create

  .form-inputs
    = f.simple_fields_for :comments do |comment|
      = render 'comments/subform', :f => comment

  .form-actions
    = f.button :submit

app/views/comments/_subform.html.slim
.nested-fields

  = f.input :content, label:"Comments", placeholder:"Your message!",
            :input_html => { :rows => 7, :cols => 25}
             

app/views/entries/_comments.html.slim
br
- @entry.comments.each do |comment|
  p
    comment.content
  comment.comment_time
  

app/views/entries/_form.html.slim
= simple_form_for(@entry) do |f|
  = f.error_notification

  fieldset.form-inputs
    legend  
    = f.input :first_name, :placeholder => 'First Name', label:false, :input_html => {:style => 'width: 7em'}
    = f.input :last_name, :placeholder => 'Last Name', label:false, :input_html => {:style => 'width: 7em'}

    div class="checkbox"
      = f.input :title, :placeholder => 'Job Title', label:'Title', :input_html => {:style => 'width: 15em'}
    div class="imageUpload"
      = f.hidden_field(:avatar_cache)
      = f.file_field(:avatar)

  = f.simple_fields_for :addresses do |address|
    = render 'addresses/form', :f => address
  
  = f.simple_fields_for :emails do |email|
    = render 'urls/email_form', :f => email
  
  = f.simple_fields_for :webs do |web|
    = render 'urls/web_form', :f => web
  
  = f.simple_fields_for :phones do |phone|
    = render 'urls/phone_form', :f => phone

  #buttons.for-actions
    = link_to "Back", entries_path 
    ' &nbsp;|
    = f.button :submit

app/views/entries/_index.html.slim
=form_tag entries_path, method: 'get' do
  =text_field_tag :search, params[:search], type: :search

ul#tab
  - ('A'..'Z').each do |i|
    - iskey = params[:initial] == i
    li class=(iskey ? 'selected' : '')
      =link_to i, entries_path(initial: i)
ul#entries
  - @entries.each do |entry|
    = render 'index_entry', entry: entry

app/views/entries/_index_entry.html.slim
- selected = @entry && @entry.id == entry.id
li class=(selected ? 'selected' : '')
  = link_to(entry_path(entry, search: params[:search])) do
    div class="image"
      = avatar(entry,66)
    div class="info"
      p class="name"
        = entry.full_name
      p class="title"
        = entry.title
   
    

app/views/entries/edit.html.slim
h1 Editing entry

== render 'form'

app/views/entries/index.html.slim
h3 Welcome to Chong Yue's Addressbook!

p
 
  = "Hello Professor Frankel,"
br
p
  = "This is the most interesting course I took at Fordham so far, thank you very much!"
br
ul
  li = "For this project, I got 94% coverage on testing and 100% on SimpleCov by ignoring some methods can't be tested. The main part that can't be tested is the cl_image_tag method from Cloudinary, which is production only."
  li = "I added a phone number attribute to each contact."
  li = "I use 'rspec' for testing and 'FactoryGirl' to replace 'fixture, so you might need to run 'rspec' instead of the original test."
  li = "Last but not the least, even this course is over, I would probably maintain this website and try to make it my personal website while keep adding beautiful stuff in future!"

p
  strong = "Note: Phone # generated by Faker could fail the validation, thus to make sure it passes I commented out the validation of phone # !"

p
  = "Best,"
p = "Chong Yue"

app/views/entries/new.html.slim
h1 New entry

== render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.slim
/p#notice = notice

div id="article-content"
  div id="avatar"
    = avatar(@entry, 500)

  div id="details"
    div class="details"
      h2 #{@entry.full_name}

      p =@entry.title

      h4 Addresses
      - @entry.addresses.each do |address|
        ul
          li = address.address_type.name
                  
          li
            = address.street.titleize
            ',
            = address.city
            ',
            = address.state
            ' 
            = address.zip
          

      h4 Emails
      - @entry.emails.each do |email|
        ul
          li = email.address_type.name
          li = link_to email.name, email.to_email

      h4 Webs
      - @entry.webs.each do |web|
        ul
          li = web.address_type.name
          li = link_to web.name, web.to_url

      h4 Phone Numbers
      - @entry.phones.each do |phone|
        ul
          li = phone.address_type.name
          li = link_to phone.name, phone.to_phone

div id="article-btn"
  = link_to 'Edit', edit_entry_path(@entry)
  '|
  = link_to 'Destroy', @entry, :confirm => 'Are you sure?', :method => :delete

app/views/layouts/application.html.slim
DOCTYPE html
html
  head
    title = 'Chong-AddressBook'
    = stylesheet_link_tag "application", media: "all"   
    = javascript_include_tag "application"
    = csrf_meta_tags 

  body
    #content
      header  
        h1 ChongYue-AddressBook
      nav 
        h2 Contacts
        = render :partial => "entries/index", :locals => { :entries =>  @entries}
        .btn
          = link_to "Add new contact", new_entry_path
          / = link_to "Home", entries_path
          / 
      article
        #notice = notice
        = yield 
      footer
        | &copy Chong.Y

app/views/urls/_email_form.html.slim
.nested-fields
  fieldset
    legend Emails
    
    div class="association"
      = f.association :address_type, label: false

    = f.input :name, label: false, placeholder: "Email" 
    
    div class="checkbox"
      = f.check_box :_destroy

app/views/urls/_phone_form.html.slim
.nested-fields
  fieldset
    legend Phone Numbers
    div class="association"
      = f.association :address_type, label: false 
  
    = f.input :name, label: false, placeholder:"Phone Number"

    div class="checkbox"
      = f.check_box :_destroy

app/views/urls/_web_form.html.slim
.nested-fields
  fieldset
    legend Websites

    div class="association"
      = f.association :address_type, label: false

    = f.input :name, label:false,  placeholder: "URL"
    
    div class="checkbox"
      = f.check_box :_destroy